### PR TITLE
migrate LaunchSuite and SuiteGenerator classes from "org.testng.xml" 

### LINKED ISSUE #562: Migrate LaunchSuite and SuiteGenerator classes from "org.testng.xml" in testng codebase to here
The below two classes reside in TestNG but it is being ONLY used by the eclipse plugin. So it would make sense that we move these classes from the TestNG codebase to the testng eclipse plugin codebase.

Classes in question:

* [LaunchSuite.java](https://github.com/testng-team/testng/blob/master/testng-core/src/main/java/org/testng/xml/LaunchSuite.java)
* [SuiteGenerator](https://github.com/testng-team/testng/blob/master/testng-core/src/main/java/org/testng/xml/SuiteGenerator.java)

The above classes are being referred to in

* `org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate`
* `org.testng.eclipse.ui.util.ConfigurationHelper`
* `org.testng.eclipse.util.CustomSuite`
* `org.testng.eclipse.util.SuiteGenerator`

Please confirm once the migration is complete and I will go ahead and remove off the above two classes from the testng codebase.

ping @missedone

### PR DESCRIPTION
**Pull request by missedone**
closes #562 

@krmahadevan , i didn't read the detail of LaunchSuite.java and SuiteGenerator.java, i simply copied them under the same package so no code change required.

### CODE REVIEW

**Review by krmahadevan — APPROVED** [review]

**Comment by krmahadevan** [comment]
@missedone - We just need to ensure that it works fine. I will go ahead with removing those 2 classes and then maybe you can vet out the eclipse plugin with the snapshot of testng 7.10.0 and check if all is well.

**Comment by missedone** [comment]
sounds good, thx @krmahadevan

**Comment by krmahadevan** [comment]
@missedone - My changes are merged to `7.10.0-SNAPSHOT`. Please give it a try.

**Review by juherr — APPROVED** [review]

**Comment by missedone** [comment]
merging this PR now.

@krmahadevan , i will raise a separate PR in testng-remote as the testing commit https://github.com/testng-team/testng/commit/94bf0111c9f721d788db21670edb352cc5fe044f breaks testng-remote after removing the arg `-port`

**Pull request merged**
